networks:
  nestjs-network:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:3-debian-10'
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper
    networks:
      - nestjs-network

  kafka:
    image: 'bitnami/kafka:2-debian-10'
    container_name: kafka
    ports:
      - 9092:9092 # Internal (Docker network)
      - 9093:9093 # External (localhost)
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_MESSAGE_MAX_BYTES=6291456 # Max message size: 6MB
      - KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=6291456 # Max message fetch size: 6MB
      - KAFKA_OPTS=-Djava.awt.headless=true
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - nestjs-network

volumes:
  zookeeper_data:
  kafka_data:
